server:
  port: 19097

spring:
  application:
    name: alert-service

  datasource:
    url: jdbc:postgresql://localhost:5432/alert_db
    username: javaauction
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: alert-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.javaauction.alertservice.presentation.dto.request.ReqPostInternalAlertsDtoV1


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

slack:
  bot:
    token: ${SLACK_BOT_TOKEN}
