spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**, /v1/auth/**, /v1/address/**, /internal/users/**, /v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user, /v3/api-docs

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/v1/products/**, /v1/categories/**, /v3/api-docs/product

        - id: auction-service
          uri: lb://auction-service
          predicates:
            - Path=/v1/auctions/**, /internal/bids/**, /v3/api-docs/auction

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/v1/wallets/**, /internal/wallets/**, /internal/deposits/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/v1/chatrooms/**

        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/v1/alerts/**, /internal/v1/alerts/**

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/v1/reviews/**, /internal/reviews/**, /v3/api-docs/review
          filters:
            - RewritePath=/v3/api-docs/review, /v3/api-docs

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

jwt:
  secret: ${JWT_SECRET}
  expiration: 1800000

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /v3/api-docs/user
      - name: product-service
        url: /v3/api-docs/product
      - name: review-service
        url: /v3/api-docs/review
