spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: javaauction
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # Redis 설정 추가 (여기부터 새로 추가)
  data:
    redis:
      host: localhost # 로컬 IntelliJ 실행 시
      port: 6379
      database: 0
      timeout: 3000ms

  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10분 (밀리초 단위)
      cache-null-values: false

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

# Swagger 설정 추가
springdoc:
  enable-querydsl: false
  api-docs:
    enabled: true
    path: /v3/api-docs/product
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha


aws:
  s3:
    bucket: java-auction-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

popular-products:
  top-count: 10  # 상위 N개
  cache-ttl-minutes: 5  # 캐시 유효 시간 (5분)
  refresh-cron: "0 * * * * *"  # 1분마다 갱신 (매 분 0초)