global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'javaauction-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']
        labels:
          service: 'gateway'
          application: 'gateway'

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8080']
        labels:
          service: 'eureka-server'
          application: 'eureka-server'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8080']
        labels:
          service: 'user-service'
          application: 'user-service'

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8080']
        labels:
          service: 'product-service'
          application: 'product-service'

  - job_name: 'auction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auction-service:8080']
        labels:
          service: 'auction-service'
          application: 'auction-service'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8080']
        labels:
          service: 'payment-service'
          application: 'payment-service'

  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-service:8080']
        labels:
          service: 'chat-service'
          application: 'chat-service'

  - job_name: 'alert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['alert-service:8080']
        labels:
          service: 'alert-service'
          application: 'alert-service'

  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['review-service:8080']
        labels:
          service: 'review-service'
          application: 'review-service'